version: '3.4'

services:
  coreapi:
    image: ${DOCKER_REGISTRY-}coreapi
    container_name: LK-CoreAPI
    build:
      context: .
      dockerfile: CoreAPI\CoreAPI\Dockerfile
    ports:
      - 52917:8080
      #- 52918:8081
    depends_on:
      - coreapi.db
  
  coreapi.db:
    image: postgres:11.4
    container_name: LK-CoreAPI-DB
    environment:
      - POSTGRES_DB=CoreAPIDB
      - POSTGRES_USER=lamkhai
      - POSTGRES_PASSWORD=@Password
    volumes:
      - coreapi-db-data:/var/lib/postgresql/data
    ports:
      - 5432

  coreapi.cache:
    image: redis:latest
    container_name: LK-CoreAPI-Cache
    restart: always
    ports:
      - 6379
 
volumes:
  coreapi-db-data: